### PR TITLE
2.1.5 g5 header

### PR DESCRIPTION
**Pull request by thescubageek**
Another round of trying to get G5 header set up and passing specs....

QA Test Beds (all looks good here):
https://g5-cms-1tbo672w-qa-test-beds.herokuapp.com/

### CODE REVIEW

**Comment by bbauer** [comment]
@thescubageek specs are passing now?

**Comment by thescubageek** [comment]
@bbauer YEEEEEHAW!!! Looks like we have passing specs... let me know if this solution is good to go for Monday whenever you feel confident.

**Comment by bbauer** [comment]
@thescubageek Yeah I think we're good to go. I've deployed this up to https://g5-cms-1tbo672w-qa-test-beds.herokuapp.com and things look good. The only think I wasn't sure about was the version. Is this still part of 2.1.4?

**Comment by thescubageek** [comment]
This will be on 2.1.5, so we can bump the subversion in the version.yml file

**Comment by thescubageek** [comment]
@bbauer ^^ This was reverted out of master because there was a bug causing the menu toggle to break. This has _not_ been merged into 2.1.5.... needs further QA before it's ready.

**Comment by bbauer** [comment]
Did you create a story around the issue? If not please do...

**Comment by thescubageek** [comment]
Yeah I'll get it done and link it in here.

**Pull request merged**
