### PR TITLE
Recompile elease iui ss cards widget ember

### PR DESCRIPTION
**Pull request by jcstringer**
Recompiles the elease iui ss cards widget, which is the output of this PR there https://github.com/g5search/sitelink-elease-iui-cards/pull/76

### CODE REVIEW

**Comment by johnlucia** [comment]
:+1:

**Comment by thescubageek** [comment]
@jcstringer Do you want this merged and shipped with CMS v2.1.1 today?

**Comment by jcstringer** [comment]
@thescubageek yes I do, however there are integration services that will need to ship with it. I say go ahead and merge it and we can deal, since customer sites would only see the changes if they are deployed.

**Comment by thescubageek** [comment]
@jcstringer This has been merged into 2.1.1-merge: https://github.com/g5search/g5-content-management-system/pull/769

**Pull request merged**
