### PR TITLE
update promoted reviews with read more

### PR DESCRIPTION
**Pull request by aaronwebre**
Adding 'Read More' link to promoted reviews widget. URL pulls from reputation api endpoint, and directs to third party review (yelp, google plus, etc.).

G5 direct reviews have a null value, so link should not appear on these.

### CODE REVIEW

**Comment by aaronwebre** [comment]
I'm not sure what's up with the show.js diff. There are a bunch of changes that aren't mine. I'll need to re-commit that.

**Comment by aaronwebre** [comment]
Made 2 trivial commits to get rid of changes that snuck into my branch. So now show.js should be master except for the addition of the fullReviewLink var.

**Comment by aaronwebre** [comment]
https://www.pivotaltracker.com/n/projects/252805/stories/99239558

**Comment by crissmancd** [comment]
Looks good but you'll have to resolve the conflicts first

**Comment by thescubageek** [comment]
Rolled out with 2.1.3

**Pull request closed without merging**
